---
title: "300323-segura-meeting"
output: html_document
date: "2023-03-29"
---

### load libraries
```{r, load}
library(tidyverse)
library(dplyr)
```

### Write function to collect data for epidermis and dermis into two dataframes
```{r, txt-to-df}
# write code in R to turn multiple txt files into one dataframe where each column corresponds to one txt file

# set working directory to folder containing txt files
collect_data <- function(path_to_folder_with_txts_as_string, file_name, type="txt"){
  # set your working directory to the folder where your txt files are located
#setwd(path_to_folder_with_txts_as_string)

# create a list of all the txt files in the folder
txt_files <- list.files(pattern = "\\.txt$")

# create an empty dataframe to hold the data
combined_df <- data.frame()

# loop through each txt file and append it to the dataframe
for (file in txt_files) {
  # read in the txt file as a dataframe
  temp_df <- read.table(file, header = TRUE)
  # append NA values to make sure all columns have the same length
  if (nrow(temp_df) < nrow(combined_df)) {
    temp_df[(nrow(temp_df)+1):nrow(combined_df),] <- NA
  } else if (nrow(temp_df) > nrow(combined_df)) {
    combined_df[(nrow(combined_df)+1):nrow(temp_df),] <- NA
  }
  # combine the temp dataframe with the combined dataframe
  combined_df <- cbind(combined_df, temp_df)
}

# rename the columns to match the original file names
colnames(combined_df) <- txt_files

# view the final dataframe
combined_df

  
  return(combined_df)
}

# In this code, setwd() sets the working directory to the folder containing the txt files. The list.files() function creates a vector of all txt file names in the directory. The data.frame() function creates an empty dataframe to store the combined data. The for loop reads in data from each txt file and appends it to the combined_data dataframe using the cbind() function. Finally, the colnames() function renames the columns of the dataframe with the names of the txt files.

#This code assumes that all of the txt files have the same structure and that they all have headers. 

```

### Collect micron epidermis and dermis pixel (unaltered) data into two dataframes
```{r, use-collect-data-fucntion}
# collect all epidermis data
  # set path
path_to_folder <- "../data/Epidermal-thickness-prism"
  #check path
list.files(path_to_folder)

all_epidermis<-collect_data(path_to_folder)


# collect all dermis data
path_to_folder2 <- "../data/Dermal-thickness-prism"
  #check path
list.files(path_to_folder2)

all_dermis<-collect_data(path_to_folder2)
```

### Save the epidermis and dermis pixel dataframes 
```{r, save-dermis-and-epidermis-dfs}
## ONLY RUN IF DATAFRAMS NOT ALREADY SAVED!

write.csv(all_epidermis, file=paste0("../data/","all_epidermis_lengths_in_pixels.csv"))
write.csv(all_dermis, file=paste0("../data/","all_dermis_lengths_in_pixels.csv"))
```
